export {default as Home} from './Home'
export {default as ChooseUs} from './ChooseUs'
export {default as Pricing} from './Pricing'
export {default as CoverWorld} from './CoverWorld'
export {default as Footer} from './Footer'